// Copyright Fillipe Romero. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace InterfaceHeroGameplayTags
{
	// Widget Stack
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WidgetStack_Modal);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WidgetStack_GameMenu);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WidgetStack_GameHud);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WidgetStack_Frontend);

	// Widgets
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_PressAnyKeyScreen);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_MainMenuScreen);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_ConfirmScreen);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_StoryScreen);
	INTERFACEHERO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_OptionsScreen);
}
